# Generated by Django 3.0.2 on 2020-04-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CueMath',
        ),
    ]
