# Generated by Django 3.0.2 on 2020-04-21 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_delete_cuemath'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrreport',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 4, 21, 6, 26, 21, 609745, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
