# Generated by Django 3.0.2 on 2020-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0003_cdrreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrreport',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
