# Generated by Django 3.0.2 on 2020-04-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0004_auto_20200421_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdrreport',
            name='time',
        ),
        migrations.AlterField(
            model_name='cdrreport',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
